2 задача- калькулятор
js-tasks-ru/vue-20231109_sasha-is-permi pull request #4
Opened 2023-11-15 23:22 UTC by sasha-is-permi

2 задача- калькулятор

2023-11-15 23:22 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-11-16 08:28 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-11-16 23:05 UTC, ShGKme requested changes

2023-11-16 23:05 UTC, ShGKme commented on 01-basics/02-VueCalculator/index.html
> +          <label><input type="radio" name="operator" value="divide" @click="action='divide'" /> ➗</label>
Здесь есть связь с состоянием приложения только в одну сторону. Выбор радиокнопки приводит к изменению состояния приложения.

Но в обратную сторону не работает. Если поменять `action` на новое значение, радиокнопка всё равно останется выделенной старая, и состояние приложения не будет соответствовать состоянию страницы.

Состояние радиокнопок `checked` должно быть привязано к состоянию приложения.

Сразу двустороннее связывание проще сделать через `v-model`.

2023-11-16 23:05 UTC, ShGKme commented on 01-basics/02-VueCalculator/script.js
> +    },
Здесь через отслеживание вручную релиазовано вычисление `result` одной функцией вычисления при изменении любой из зависимостей вычисления. Фактически реализовано вычисляемое свойство, но вручную. Такие свойства нужно реализовывать именно как вычисляемое свойство `computed`:

- Явно. Так `result` будет описан именно как вычисляемый, а не как самостоятельное свойство с собственным значением
- Не нужно самостоятельно определять зависимости отслеживания и для каждого делать одинаковые действия
- Эффективнее - вычисляемые свойства ленивые и вычисляются только, когда к их значению обращаются

2023-11-16 23:05 UTC, ShGKme commented on 01-basics/03-MarkedList/index.html
> +          Я думал- ключи должны добавляться без кавычек-->
При выводе Vue сериализует объект в JSON. В JSON ключи всегда в двойных кавычках

2023-11-16 23:05 UTC, ShGKme commented on 01-basics/03-MarkedList/script.js
> +  }
Это вычисляемое свойство в процессе вычисления нового значения побочным эффектом мутирует состояние компонента 

Вычисляемые свойства ни в коем случае не должны иметь побочных эффектов. Мы не контролируем, когда оно вычисляется и пере-вычисляется. Факт его вычисления должен только давать значение, но не изменять состояние приложения.

В целом в `map` не принято мутировать элементы массива, на основе которого создаётся новый.

2023-11-17 07:31 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-11-17 08:59 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-11-17 09:02 UTC, sasha-is-permi commented
Исправил замечания по калькулятору и по списку

2023-11-17 09:16 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-11-17 09:24 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-11-17 09:29 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-11-17 21:13 UTC, ShGKme approved these changes
Все задачи приняты 👍

2023-11-17 21:13 UTC, merged